# Generated by Django 2.1.3 on 2018-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181203_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
