# Generated by Django 2.1.3 on 2018-12-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
    ]
